# Generated by Django 4.1 on 2024-03-27 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wall_name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('img_width', models.PositiveIntegerField()),
                ('img_height', models.PositiveIntegerField()),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.gym')),
            ],
        ),
    ]
