# Generated by Django 4.1 on 2024-03-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walls', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wall',
            constraint=models.UniqueConstraint(fields=('gym', 'wall_name'), name='unique_wall_name_per_gym'),
        ),
    ]
