# Generated by Django 4.1 on 2024-03-29 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boulders', '0003_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='boulder',
            name='grade',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(17)]),
        ),
    ]
