# Generated by Django 4.2.11 on 2024-04-15 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boulders', '0004_boulder_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='sender',
            name='flash',
            field=models.BooleanField(default=True),
        ),
    ]
