# Generated by Django 4.2.11 on 2024-04-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boulders', '0005_sender_date_sender_flash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='flash',
            field=models.BooleanField(),
        ),
    ]
