# Generated by Django 4.1 on 2024-03-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_remove_gym_num_walls'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gym',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_gym_name'),
        ),
    ]
